h = int(input(""))

if h == 0:
    print (" * * *")
    print ("*     *")
    print ("*     *")
    print ("*     *")
    print ("       ")
    print ("*     *")
    print ("*     *")
    print ("*     *")
    print (" * * *")
elif h == 1:
    print ("")
    print ("      *")
    print ("      *")
    print ("      *")
    print ("")
    print ("      *")
    print ("      *")
    print ("      *")
    print ("")
elif h == 2:
    print (" * * *")
    print ("      *")
    print ("      *")
    print ("      *")
    print (" * * * ")
    print ("*      ")
    print ("*      ")
    print ("*      ")
    print (" * * *")
elif h == 3:
    print (" * * *")
    print ("      *")
    print ("      *")
    print ("      *")
    print (" * * * ")
    print ("      *")
    print ("      *")
    print ("      *")
    print (" * * *")
elif h == 4:
    print ("       ")
    print ("*     *")
    print ("*     *")
    print ("*     *")
    print (" * * * ")
    print ("      *")
    print ("      *")
    print ("      *")
    print ("       ")
elif h == 5:
    print (" * * * ")
    print ("*      ")
    print ("*      ")
    print ("*      ")
    print (" * * * ")
    print ("      *")
    print ("      *")
    print ("      *")
    print (" * * * ")
elif h == 6:
    print (" * * * ")
    print ("*      ")
    print ("*      ")
    print ("*      ")
    print (" * * * ")
    print ("*     *")
    print ("*     *")
    print ("*     *")
    print (" * * * ")
elif h == 7:
    print (" * * * ")
    print ("      *")
    print ("      *")
    print ("      *")
    print ("")
    print ("      *")
    print ("      *")
    print ("      *")
    print ("      *")
    print ("       ")
elif h == 8:
    print (" * * * ")
    print ("*     *")
    print ("*     *")
    print ("*     *")
    print (" * * * ")
    print ("*     *")
    print ("*     *")
    print ("*     *")
    print (" * * * ")
elif h == 9:
    print (" * * * ")
    print ("*     *")
    print ("*     *")
    print ("*     *")
    print (" * * * ")
    print ("      *")
    print ("      *")
    print ("      *")
    print (" * * * ")